# configs/baseline.yaml

model:
  name: CNN
  input_dim: 96
  num_classes: 10
  seed: 42
  use_cuda: True
  learning_rate: 0.0003
  weight_decay: 0.05
  optimizer: adam
  momentum: 0.9

train:
  samples_per_class: 400
  total_epochs: 200
  warmup_epochs: 5
  batch_size: 512
  num_workers: 4
  print_interval: 10
  output_dir_suffix: cnn_400
  verbose: True
  
test:
  batch_size: 512
  num_workers: 4
  output_dir_suffix: cnn_400

logging:
  print_interval: 10
  output_dir: outputs/baseline/
  model_path: cnn.pt