# configs/baseline.yaml

model:
  input_dim: 64
  num_channels: 3
  conv1_out_channels: 8
  conv1_kernel_size: 3
  pool_kernel_size: 2
  pool_stride: 2
  conv2_out_channels: 32
  conv2_kernel_size: 3
  conv3_out_channels: 64
  conv3_kernel_size: 3
  lin_in_features: 2304 # 64*6*6
  lin_out_features: 64
  dropout_p: 0.5
  out_features: 10

train:
  samples_per_class: 400
  total_epochs: 100
  warmup_epochs: 5
  batch_size: 512
  learning_rate: 0.0003
  weight_decay: 0.05
  num_workers: 4
  output_dir_suffix: cnn_400

testing:
  batch_size: 128

logging:
  print_interval: 10
  output_dir: outputs/baseline/